import type { UiDictionary } from "./types";

export const uiEn: UiDictionary = {
  nav: {
    apartments: "Apartments",
    location: "Where we are",
    about: "About us",
    reviews: "Reviews",
    contact: "Contact",
    book: "Book",
    call: "Call",
    menu: "Menu",
    close: "Close",
  },
  hero: {
    badge: "Lepetane, Tivat",
    headline: "The sea at your door. The Bay of Kotor behind you.",
    ctaApartments: "See the apartments",
    ctaAvailability: "Check availability",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Guests",
    apartment: "Apartment",
    anyApartment: "Any",
    search: "Check",
  },
  apartments: {
    kicker: "Rented in full",
    heading: "Our apartments",
    lead: "Every apartment is rented in full — the space is yours alone. They are spacious, clean, with a balcony or terrace, a private entrance, and everything needed for a quiet stay by the sea.",
    filterAll: "All",
    filterStudio: "Studio",
    filterFamily: "Family",
    filterFive: "Up to 5 guests",
    capacity: "guests",
    fromPrice: "",
    perNight: "/ day",
    details: "Details",
    book: "Book",
    size: "Size",
    bedrooms: "Bedrooms",
    studioLayout: "Studio",
    bathrooms: "Bathrooms",
    beds: "Beds",
    close: "Close",
    gallery: "Gallery",
    prev: "Previous photo",
    next: "Next photo",
    occupied: "Occupied",
    back: "Our apartments",
    availability: "Check availability",
    enquireThis: "Book this apartment",
    photoCount: "photos",
    openGallery: "View photos",
  },
  amenities: {
    kicker: "Why here",
    heading: "Quiet by the sea. Close to everything, far from the crowds.",
    lead: "On Booking.com we have a 9.7 score from more than 185 reviews.",
  },
  about: {
    kicker: "The Nikić family",
    heading: "Welcome to Apartmani Nikić",
    lead: "We are at the very entrance to the Bay of Kotor, in a small, quiet place called Lepetane, between Tivat and the ferry to Kamenari.",
    body: [
      "The beach is in front of the house, the mountains are behind you, and there is nothing between you and the sea except a few steps. Irena and the family greet every guest in person.",
      "If you are looking for a place to actually rest, not just change location, you are welcome. There is no reception, no call centre, no bot that answers automatically. When you write or call, Irena answers — the owner, who knows every apartment and the available dates.",
    ],
    hostsLabel: "Hosts",
    welcome: "Irena and the family greet every guest in person.",
  },
  location: {
    kicker: "Lepetane · Tivat",
    heading: "We are at the entrance to the Bay of Kotor",
    lead: "Lepetane is an ideal base for exploring the whole Bay of Kotor. Kotor, Perast, Porto Montenegro and Herceg Novi are all within easy reach — and when you return, the quiet and the sea in front of the house are waiting.",
    body: "The beach is literally in front of the apartments — not a five-minute walk, but fifty metres from our gate. You step out, cross the road, and you are already in the sea. The beach is only 50m from the apartments.",
    directions: "Exactly where we are",
    addressLabel: "Address",
  },
  reviews: {
    kicker: "Booking.com",
    heading: "What our guests say",
    lead: "Guests rate us exceptionally highly — on Booking.com and Airbnb.",
    badge: "Excellent",
    basedOn: "Based on more than {n} verified reviews",
    verified: "Verified Booking.com guest",
    prev: "Previous review",
    next: "Next review",
  },
  booking: {
    kicker: "Direct booking",
    heading: "Book your stay",
    lead: "Choose an apartment and dates. The host will contact you.",
    name: "Full name",
    email: "Email",
    phone: "Phone / WhatsApp",
    dates: "Dates",
    checkIn: "Check-in",
    checkOut: "Check-out",
    apartment: "Apartment",
    selectApartment: "Select an apartment",
    guests: "Number of guests",
    message: "Message (optional)",
    messageHint: "Late arrival, airport transfer…",
    submit: "Confirm enquiry",
    whatsapp: "Message on WhatsApp",
    successTitle: "Thank you for your enquiry",
    successBody:
      "Your reservation request has been received. Host Irena and the Nikić family will contact you shortly to confirm availability.",
    successCall: "Call the host now",
    successWhatsapp: "Open WhatsApp chat",
    selectedRange: "Selected dates",
    estimatedTotal: "Estimated total",
    night: "night",
    nights: "nights",
    summaryPeriod: "Dates",
    summaryGuests: "Guests",
    close: "Close",
    errors: {
      name: "Please enter your full name.",
      email: "Please enter a valid email.",
      phone: "Please enter a phone or WhatsApp number.",
      checkIn: "Please choose a check-in date.",
      checkOut: "Please choose a check-out date.",
      range: "Check-out must be after check-in.",
      minStay: "A minimum stay of 3 days is required.",
      apartment: "Please select an apartment.",
      guests: "Please enter the number of guests.",
      capacity: "Guest count exceeds this apartment’s capacity.",
      booked: "The selected dates are not free for this apartment.",
    },
    note: "Check-in is from 15:00 to 23:00. Check-out is from 08:00 to 10:00. Minimum 3 days. 30% deposit.",
    policies: "Unfortunately, for now we do not allow pets in our apartments. Smoking is not allowed in the apartments. A separate area is provided for that purpose.",
    stepApartment: "Apartment",
    stepDates: "Dates",
    stepDetails: "Details",
    next: "Next",
    back: "Back",
  },
  video: {
    kicker: "YouTube",
    heading: "See the Bay and our apartments on video",
    lead: "Clips from the terrace, the apartments and the beach in Lepetane.",
    play: "Play video",
    close: "Close video",
    channelLead: "Watch every clip of the Bay of Kotor and our apartments on the official YouTube channel.",
    channelCta: "Follow our YouTube channel",
  },
  calendar: {
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    days: ["M", "T", "W", "T", "F", "S", "S"],
    free: "Free",
    busy: "Occupied",
    selectCheckIn: "Choose a check-in date.",
    selectCheckOut: "Choose a check-out date.",
    rangeBlocked: "The selected period includes occupied nights.",
    selected: "Selected",
    clearDates: "Clear dates",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    loading: "Loading calendar…",
    occupiedBanner: "THE APARTMENT IS OCCUPIED",
    occupiedBody: "This apartment is not currently free for new dates. You can still write to us with other questions.",
    unavailable: "The calendar is temporarily unavailable. Include dates in your message or write on WhatsApp.",
  },
  footer: {
    tagline: "Apartmani Nikić – family-run apartments in Lepetane, Tivat, right on the shore.",
    contact: "Contact",
    stay: "Your stay",
    social: "Social",
    checkIn: "Check-in",
    checkOut: "Check-out",
    directions: "Google Maps",
    rights: "All rights reserved.",
    agency: "Website prepared by SvojSmeštaj",
  },
  mobileBar: {
    call: "Call",
    whatsapp: "WhatsApp",
    book: "Enquire",
  },
};
