import type { UiDictionary } from "./types";

export const uiSr: UiDictionary = {
  nav: {
    apartments: "Naši apartmani",
    location: "Gdje se nalazimo?",
    about: "O nama",
    reviews: "Utisci",
    contact: "Kontakt",
    book: "Rezervišite",
    call: "Pozovite",
    menu: "Meni",
    close: "Zatvori",
  },
  hero: {
    badge: "Lepetane, Tivat",
    headline: "More ispred vrata. Boka Kotorska u pozadini.",
    ctaApartments: "Pogledajte apartmane",
    ctaAvailability: "Provjerite dostupnost",
    checkIn: "Prijava",
    checkOut: "Odjava",
    guests: "Gosti",
    apartment: "Apartman",
    anyApartment: "Bilo koji",
    search: "Provjeri",
  },
  apartments: {
    kicker: "Izdaju se u cjelosti",
    heading: "Naši apartmani",
    lead: "Svaki apartman se izdaje u cjelosti - prostor samo za vas. Prostrani su, čisti, sa balkonom ili terasom, privatnim ulazom i svime što treba za miran boravak uz more.",
    filterAll: "Svi",
    filterStudio: "Studio",
    filterFamily: "Porodični",
    filterFive: "Do 5 osoba",
    capacity: "osoba",
    fromPrice: "",
    perNight: "/ dan",
    details: "Detaljnije",
    book: "Rezervišite",
    size: "Površina",
    bedrooms: "Spavaće sobe",
    studioLayout: "Studio",
    bathrooms: "Kupatila",
    beds: "Ležaja",
    close: "Zatvori",
    gallery: "Galerija apartmana",
    prev: "Prethodna fotografija",
    next: "Sljedeća fotografija",
    occupied: "Zauzet",
    back: "Naši apartmani",
    availability: "Provjerite dostupnost",
    enquireThis: "Rezervišite ovaj apartman",
    photoCount: "fotografija",
  },
  amenities: {
    kicker: "Zašto ovdje",
    heading: "Miran smještaj uz more. Blizu svega, a daleko od gužve.",
    lead: "Na Booking.com portalu imamo ocjenu 9.7 od više od 185 recenzija.",
  },
  about: {
    kicker: "Porodica Nikić",
    heading: "Dobrodošli u apartmane Nikić",
    lead: "Nalazimo se na samom ulazu u Boku Kotorsku, u malom, mirnom mjestu po imenu Lepetane, između Tivta i trajektne veze za Kamenare.",
    body: [
      "Plaža je ispred kuće, planine su u pozadini i nema ničega između vas i mora osim par koraka. Irena i porodica dočekuju svakog gosta lično.",
      "Ako tražite mjesto gdje ćete stvarno odmoriti, ne samo promijeniti lokaciju, dobro ste došli. Nema recepcije, nema Call centra, nema bota koji odgovara automatski. Kad nam pišete ili nas zovete javlja se Irena - vlasnica, koja zna svaki apartman i dostupne termine.",
    ],
    hostsLabel: "Domaćini",
    welcome: "Irena i porodica dočekuju svakog gosta lično.",
  },
  location: {
    kicker: "Lepetane · Tivat",
    heading: "Nalazimo se na ulazu u Boku Kotorsku",
    lead: "Lepetane su idealna baza za istraživanje cijele Boke Kotorske. Kotor, Perast, Porto Montenegro i Herceg Novi su svi nadohvat ruke - a kad se vratite, čeka vas mir i more ispred kuće.",
    body: "Plaža je bukvalno ispred apartmana - ne pet minuta hoda, nego pedeset metara od naše kapije. Izađete, pređete put i već ste u moru. Plaža je na svega 50m od apartmana.",
    directions: "Gdje se tačno nalazimo",
    addressLabel: "Adresa",
  },
  reviews: {
    kicker: "Booking.com",
    heading: "Utisci gostiju",
    lead: "Na Booking.com portalu imamo ocjenu 9.7 od više od 185 recenzija.",
    badge: "Odličan",
    basedOn: "Zasnovano na {n} recenzije",
    verified: "Objavljeno na Booking",
    prev: "Prethodni utisak",
    next: "Sljedeći utisak",
  },
  booking: {
    kicker: "Direktna rezervacija",
    heading: "Rezervišite na vrijeme vaše ljeto u Tivtu.",
    lead: "Termini se brzo popunjavaju. Javite nam se. Kad nam pišete ili nas zovete javlja se Irena.",
    name: "Ime i prezime",
    email: "E-mail",
    phone: "Telefon / WhatsApp",
    dates: "Datumi",
    checkIn: "Prijava",
    checkOut: "Odjava",
    apartment: "Apartman",
    selectApartment: "Odaberite apartman",
    guests: "Broj gostiju",
    message: "Poruka (opciono)",
    messageHint: "Dolazak kasnije, prevoz od aerodroma…",
    submit: "Pošaljite upit",
    whatsapp: "Pišite na WhatsApp",
    successTitle: "Upit je spreman",
    successBody: "Otvara se WhatsApp sa vašom porukom. Ako se nije otvorio, kopirajte broj i pišite nam direktno.",
    close: "Zatvori",
    errors: {
      name: "Unesite ime i prezime.",
      email: "Unesite ispravan e-mail.",
      phone: "Unesite telefon ili WhatsApp broj.",
      checkIn: "Odaberite datum prijave.",
      checkOut: "Odaberite datum odjave.",
      range: "Odjava mora biti poslije prijave.",
      minStay: "Minimum 3 dana boravka je potrebno rezervisati.",
      apartment: "Odaberite apartman.",
      guests: "Unesite broj gostiju.",
      capacity: "Broj gostiju premašuje kapacitet apartmana.",
      booked: "Odabrani termini nisu slobodni za ovaj apartman.",
    },
    note: "Check-In je od 15:00 do 23:00. Check-Out je od 08:00 do 10:00. Minimum 3 dana boravka. Depozit 30%.",
    policies: "Nažalaost, za sada ne dozvoljavamo kućne ljubimce u našim apartmanima. U apartmanima nije dozvoljeno pušenje. Poseban prostor postoji za tu namenu.",
  },
  calendar: {
    months: [
      "Januar",
      "Februar",
      "Mart",
      "April",
      "Maj",
      "Jun",
      "Jul",
      "Avgust",
      "Septembar",
      "Oktobar",
      "Novembar",
      "Decembar",
    ],
    days: ["P", "U", "S", "Č", "P", "S", "N"],
    free: "Slobodno",
    busy: "Zauzeto",
    selectCheckIn: "Odaberite datum prijave.",
    selectCheckOut: "Odaberite datum odjave.",
    rangeBlocked: "U odabranom periodu ima zauzetih noći.",
    selected: "Odabrano",
    clearDates: "Obrišite datume",
    prevMonth: "Prethodni mjesec",
    nextMonth: "Sljedeći mjesec",
    loading: "Učitavanje kalendara…",
    occupiedBanner: "APARTMAN JE ZAUZET",
    occupiedBody: "Ovaj apartman trenutno nije slobodan za nove termine. Možete nam i dalje pisati za druga pitanja.",
    unavailable: "Kalendar trenutno nije dostupan. Odaberite termine u poruci ili pišite na WhatsApp.",
  },
  footer: {
    tagline: "Apartmani Nikić – porodični smještaj u Lepetanima, Tivat, direktno uz obalu.",
    contact: "Kontakt",
    stay: "Boravak",
    social: "Društvene mreže",
    checkIn: "Prijava",
    checkOut: "Odjava",
    directions: "Google Maps",
    rights: "Sva prava zadržana.",
    agency: "Sajt pripremila agencija SvojSmeštaj",
  },
  mobileBar: {
    call: "Poziv",
    whatsapp: "WhatsApp",
    book: "Upit",
  },
};
